#!/bin/bash



export DEBIAN_FRONTEND=noninteractive


echo "Copy rc.local"
cp /opt/CloudLocalNetAgent/system/etc/rc.local /etc/rc.local


mount /dev/cdrom /media

cd /media

yes | ./VBoxLinuxAdditions.run


apt -y update

apt-get -y install dkms linux-headers-$(uname -r) build-essential
apt-get -y install libxt6 libxmu6

reboot
